from dataclasses import dataclass, field


@dataclass
class SemanticPerformanceAnalysis:
    """
    Semantic interpretation of a structured debate
    performance summary.

    The interpretation is generated by an LLM, while the
    underlying performance data comes from deterministic
    analysis.
    """

    overall_interpretation: str
    strengths_interpretation: str = ""
    weaknesses_interpretation: str = ""
    coaching_interpretation: str = ""
    key_insights: list[str] = field(
        default_factory=list
    )

    def __post_init__(self) -> None:
        if not self.overall_interpretation.strip():
            raise ValueError(
                "Overall interpretation cannot be empty."
            )

        self.overall_interpretation = (
            self.overall_interpretation.strip()
        )

        self.strengths_interpretation = (
            self.strengths_interpretation.strip()
        )

        self.weaknesses_interpretation = (
            self.weaknesses_interpretation.strip()
        )

        self.coaching_interpretation = (
            self.coaching_interpretation.strip()
        )

        self.key_insights = [
            insight.strip()
            for insight in self.key_insights
            if insight and insight.strip()
        ]