import json

from google import genai

from debate_arena.debate.strategy import DebateStrategy


class DebateResponse:
    """
    Structured response generated by the LLM for a debate rebuttal.
    """

    def __init__(
        self,
        rebuttal: str,
        strategy: DebateStrategy,
    ) -> None:
        self.rebuttal = rebuttal
        self.strategy = strategy


class LLMClient:
    """
    Wrapper around the Gemini API.

    This class centralizes all LLM-related operations used
    throughout the debate application.
    """

    def __init__(
        self,
        api_key: str | None = None,
        model: str = "gemini-3.5-flash-lite",
    ) -> None:
        if api_key is None:
            import os

            api_key = os.getenv("GEMINI_API_KEY")

        if not api_key:
            raise ValueError(
                "GEMINI_API_KEY is not configured."
            )

        self.client = genai.Client(
            api_key=api_key,
        )

        self.model = model

    # ------------------------------------------------------------------
    # Debate response generation
    # ------------------------------------------------------------------

    def generate_debate_response(
        self,
        prompt: str,
    ) -> DebateResponse:
        if not prompt.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "response_schema": {
                    "type": "object",
                    "properties": {
                        "rebuttal": {
                            "type": "string",
                        },
                        "strategy": {
                            "type": "string",
                        },
                    },
                    "required": [
                        "rebuttal",
                        "strategy",
                    ],
                },
            },
        )

        if not response.text:
            raise RuntimeError(
                "Gemini returned an empty debate response."
            )

        try:
            data = json.loads(response.text)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                "Gemini returned invalid debate-response JSON."
            ) from exc

        if not isinstance(data, dict):
            raise RuntimeError(
                "Gemini returned an invalid debate-response structure."
            )

        rebuttal = data.get("rebuttal")

        if not rebuttal or not rebuttal.strip():
            raise RuntimeError(
                "Gemini returned an empty rebuttal."
            )

        strategy_value = data.get(
            "strategy",
            DebateStrategy.DIRECT_COUNTER.value,
        )

        try:
            strategy = DebateStrategy(
                strategy_value
            )
        except ValueError:
            strategy = DebateStrategy.DIRECT_COUNTER

        return DebateResponse(
            rebuttal=rebuttal.strip(),
            strategy=strategy,
        )

    # ------------------------------------------------------------------
    # Argument analysis
    # ------------------------------------------------------------------

    def analyze_argument(
        self,
        argument: str,
    ) -> dict:
        if not argument.strip():
            raise ValueError(
                "Argument cannot be empty."
            )

        response = self.client.models.generate_content(
            model=self.model,
            contents=argument,
            config={
                "response_mime_type": "application/json",
                "response_schema": {
                    "type": "object",
                    "properties": {
                        "claim": {
                            "type": "string",
                        },
                        "reasoning": {
                            "type": "string",
                        },
                        "assumptions": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "evidence": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "weaknesses": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "argument_type": {
                            "type": "string",
                        },
                    },
                    "required": [
                        "claim",
                        "reasoning",
                        "assumptions",
                        "evidence",
                        "weaknesses",
                        "argument_type",
                    ],
                },
            },
        )

        if not response.text:
            raise RuntimeError(
                "Gemini returned an empty argument analysis."
            )

        try:
            data = json.loads(response.text)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                "Gemini returned invalid argument-analysis JSON."
            ) from exc

        if not isinstance(data, dict):
            raise RuntimeError(
                "Gemini returned an invalid argument-analysis structure."
            )

        return data

    # ------------------------------------------------------------------
    # Communication analysis
    # ------------------------------------------------------------------
        # ------------------------------------------------------------------
    # Complete debate analysis
    # ------------------------------------------------------------------

    def analyze_debate(
        self,
        debate_data: dict,
    ) -> dict:
        """
        Analyze the user's complete debate performance.

        The caller provides the complete debate history and
        metadata. Gemini returns a structured JSON analysis.
        """

        if not debate_data:
            raise ValueError(
                "Debate data cannot be empty."
            )

        prompt = (
            "Analyze the user's complete performance in the debate "
            "described below.\n\n"
            "Focus only on the user's performance, arguments, "
            "reasoning, evidence usage, consistency, and "
            "responsiveness to the AI opponent.\n\n"
            "Return a balanced and specific analysis based only "
            "on the supplied debate history.\n\n"
            "Debate data:\n"
            f"{json.dumps(debate_data, indent=2)}"
        )

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "response_schema": {
                    "type": "object",
                    "properties": {
                        "summary": {
                            "type": "string",
                        },
                        "strongest_argument": {
                            "type": "string",
                        },
                        "weakest_argument": {
                            "type": "string",
                        },
                        "strengths": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "weaknesses": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "evidence_usage": {
                            "type": "string",
                        },
                        "consistency": {
                            "type": "string",
                        },
                        "responsiveness": {
                            "type": "string",
                        },
                        "recommendations": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                    },
                    "required": [
                        "summary",
                        "strongest_argument",
                        "weakest_argument",
                        "strengths",
                        "weaknesses",
                        "evidence_usage",
                        "consistency",
                        "responsiveness",
                        "recommendations",
                    ],
                },
            },
        )

        if not response.text:
            raise RuntimeError(
                "Gemini returned an empty debate analysis."
            )

        try:
            data = json.loads(response.text)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                "Gemini returned invalid debate-analysis JSON."
            ) from exc

        if not isinstance(data, dict):
            raise RuntimeError(
                "Gemini returned an invalid debate-analysis structure."
            )

        return data
    def analyze_communication(
        self,
        prompt: str,
    ) -> dict:
        if not prompt.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "response_schema": {
                    "type": "object",
                    "properties": {
                        "clarity": {
                            "type": "string",
                        },
                        "conciseness": {
                            "type": "string",
                        },
                        "delivery": {
                            "type": "string",
                        },
                        "strengths": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "weaknesses": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "recommendations": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                    },
                    "required": [
                        "clarity",
                        "conciseness",
                        "delivery",
                        "strengths",
                        "weaknesses",
                        "recommendations",
                    ],
                },
            },
        )

        if not response.text:
            raise RuntimeError(
                "Gemini returned an empty communication analysis."
            )

        try:
            data = json.loads(response.text)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                "Gemini returned invalid communication-analysis JSON."
            ) from exc

        if not isinstance(data, dict):
            raise RuntimeError(
                "Gemini returned an invalid communication-analysis structure."
            )

        return data

    # ------------------------------------------------------------------
    # Responsiveness analysis
    # ------------------------------------------------------------------

    def analyze_responsiveness(
        self,
        prompt: str,
    ) -> dict:
        if not prompt.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "response_schema": {
                    "type": "object",
                    "properties": {
                        "responsiveness": {
                            "type": "string",
                        },
                        "addressed_points": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "ignored_points": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                    },
                    "required": [
                        "responsiveness",
                        "addressed_points",
                        "ignored_points",
                    ],
                },
            },
        )

        if not response.text:
            raise RuntimeError(
                "Gemini returned an empty responsiveness analysis."
            )

        try:
            data = json.loads(response.text)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                "Gemini returned invalid responsiveness-analysis JSON."
            ) from exc

        if not isinstance(data, dict):
            raise RuntimeError(
                "Gemini returned an invalid responsiveness-analysis structure."
            )

        return data

    # ------------------------------------------------------------------
    # Consistency analysis
    # ------------------------------------------------------------------

    def analyze_consistency(
        self,
        prompt: str,
    ) -> dict:
        """
        Analyze semantic consistency across the user's
        debate arguments.

        The caller provides the complete consistency-analysis
        prompt. Gemini returns structured JSON.
        """

        if not prompt.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "response_schema": {
                    "type": "object",
                    "properties": {
                        "consistency": {
                            "type": "string",
                        },
                        "consistent_points": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                        "inconsistent_points": {
                            "type": "array",
                            "items": {
                                "type": "string",
                            },
                        },
                    },
                    "required": [
                        "consistency",
                        "consistent_points",
                        "inconsistent_points",
                    ],
                },
            },
        )

        if not response.text:
            raise RuntimeError(
                "Gemini returned an empty consistency analysis."
            )

        try:
            data = json.loads(response.text)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                "Gemini returned invalid consistency-analysis JSON."
            ) from exc

        if not isinstance(data, dict):
            raise RuntimeError(
                "Gemini returned an invalid consistency-analysis structure."
            )

        return data

    def analyze_evidence_reasoning(
        self,
        prompt: str,
    ) -> dict:
        response = self.client.models.generate_content(
        model=self.model,
        contents=prompt,
        config={
            "response_mime_type": "application/json",
        },
    )
        return json.loads(response.text)    

    def analyze_semantic_performance(
        self,
        prompt: str,
    ) -> dict:
        response = self.client.models.generate_content(
        model=self.model,
        contents=prompt,
        config={
            "response_mime_type": "application/json",
        },
    )
        return json.loads(response.text)  


    def analyze_advanced_debate_performance(self, prompt: str) -> dict:
        """
        Ask Gemini to perform advanced semantic interpretation of
        already-computed debate performance data.
        """
        if not prompt or not prompt.strip():
            raise ValueError("Prompt cannot be empty.")

        response = self.client.models.generate_content(
        model=self.model,
        contents=prompt,
        config={"response_mime_type": "application/json"},
        )

        return json.loads(response.text)

    def analyze_cross_round_performance(self, prompt: str) -> dict:
        """
        Ask Gemini to perform semantic interpretation of
        deterministic cross-round debate-performance findings.
        """
        if not prompt or not prompt.strip():
            raise ValueError("Prompt cannot be empty.")

        response = self.client.models.generate_content(
        model=self.model,
        contents=prompt,
        config={"response_mime_type": "application/json"},
        )

        return json.loads(response.text)    

    def analyze_moment_analysis(
        self,
        prompt: str,
    ) -> dict:
        """
        Send the strongest/weakest moment interpretation prompt
         to Gemini and return the parsed JSON response.
        """

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
            },
        )

        return json.loads(response.text)    